
category_name:
  type: string
  default: Staff
  description: Show sidebar for this category (case-sensitive)

sidebar_alignment:
  default: right
  type: enum
  choices:
    - left
    - right

headline: 
  type: string
  default: "Sidebar"
  description: Optional. Leave blank for none. 

intro: 
  type: string
  default: "Welcome to the sidebar"
  description: Optional. Leave blank for none. 

list_items: 
  type: list
  default: 
    "subhead, your subhead text|link, your link text, https://example.com|text, your text here"
  description: You can add lists with section headers above. <ul><li><b>Subheads:</b> format your option as "subhead, subhead text"</li><li><b>Links:</b> use "link, your link text, https://example.com"</li><li><b>Text:</b> format as "text, your text here"</ul>
